### ISSUE TITLE
As a user, I want a CLI to walk me through the installation process instead of having to decipher the readme and fill the `vars` file

### ISSUE THREAD

**Issue by AlexisVLRT** [artefactory/one-click-mlflow#49]
As a User I want to be guided through the install process. I want to be explained the options I have and what they imply so I can taylor my deployment to my needs and environment

I want an intuitive and easy to use CLI that will prompt me step by step. I need the tool to be transparent regarding what it will deploy.

![image](https://user-images.githubusercontent.com/26208387/110832047-2b202200-829b-11eb-8b49-52751f3abc1d.png)

**Comment by AlexisVLRT** [comment]
@griseau Hey there, watcha think?

**Comment by griseau** [comment]
Hey @AlexisVLRT, agree with you on the prompting solution ! 

For the network, I'll maybe add a 3rd option, join an already existing network. We should not import the network, but only use it
For brand part, I would not recommend to import it or give the possibility to the user to change it. As it could be managed by other people (or terraform repository) and break things on their side, so better to just use it I think. 
For the app engine part it's already the case I think ?

**Comment by AlexisVLRT** [comment]
Solved by #55
